name: SketchVAE
paras:
    embed_dim: 256
    n_embed: 2048
    kl_weight: 0.0000045
    ddconfig:
      double_z: True
      z_channels: 16
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
