name: MSLDM
paras:
  unet_model: "sparse"
  use_ema: True
  multi_restore_batch_size: 4

  ##############
  # first second third
  level: 'first'
  ##############

  add_noise_da: true
  classifier_free_guidance: true


  use_sketch_condition: True
  use_sketch_attention: True
  sketch_condition_manner: 'cat'


  # noise schedule
  noise_schedule:
    first:
      num_train_timesteps: 1000
      clip_sample: false
      beta_schedule: "cos"
    second:
      num_train_timesteps: 1000
      clip_sample: false
      beta_schedule: "cos"
    third:
      num_train_timesteps: 1000
      clip_sample: True
      beta_schedule: "cos"
      clip_sample_range: 3.0

  sketch_embedder:
    model_class: SketchVAE
    config_file: model/sketch_vae.yaml
    ckpt: "/home/xlju/pro/diffs/output/2023-11-29-16-06-47-sk_vae_finetune/model_paras_log/model_ckpt-epoth20-globalstep310794-2023-11-29-17-24-27.pt"

  # latent encoding
  first_stage_model:
    model_class: MSTSDFPVQGANNew
    config_file: model/tsdf_vqgan_retrain.yaml
    ckpt: "model_ckpt-epoth844-globalstep399056-2023-10-21-20-19-53.pt"
############################################################################
  # diffusion network
  unet_model:
    first: 
      ckpt: "model_ckpt-epoth979-globalstep258060val_ema-2023-12-08-15-37-28.pt"
      model_type: UNetModel
      model_args:
        dims: 3
        is_sparse: True
        use_bev: True
        in_channels: 8
        out_channels: 4
        model_channels: 64
        attention_resolutions: [1,2] #for text
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        use_spatial_transformer: True

        transformer_depth: 1
        context_dim: 256

        num_heads: 8
        use_checkpoint: True
        legacy: False
        use_position_encoding: True
    second: 
      ckpt: "model_ckpt-epoth494-globalstep368775val_ema-2023-10-27-09-39-59.pt"
      model_type: UNetModel
      model_args:
        dims: 3
        is_sparse: True
        use_bev: False
        in_channels: 8 # with condition
        out_channels: 4
        model_channels: 64
        use_spatial_transformer: False
        attention_resolutions: []
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 8
        num_head_channels: 32
    third: 
      ckpt: "model_ckpt-epoth104-globalstep156450val_ema-2023-10-27-15-35-58.pt"
      model_type: UNetModel
      model_args:
        dims: 3
        is_sparse: True
        use_bev: False
        in_channels: 9
        out_channels: 1
        model_channels: 64
        use_spatial_transformer: False
        attention_resolutions: []
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 8
        num_head_channels: 32
